answer_writing_task:
  description: >
    Write a nice and informed answer to the question {question} about a car manual.
  expected_output: >
    A factually correct and fully rounded ansewr to the question. With references that will help user make informed decisions related to the cars.

query_writing_task:
  description: >
    Write a query to fetch relevant documents from the database for the question {question}.
  expected_output: >
    A query that will fetch relevant documents from the database.
    # TODO: make this prompt more robust with few shot examples.
